{{- if .Values.serviceAccount.create -}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-appdb
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-appdb
roleRef:
  kind: Role
  name: mongodb-kubernetes-appdb
  apiGroup: rbac.authorization.k8s.io
{{- end }}
